// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0c13zI1sQRRKlNGQ-VBTTd1C4gtZskKQ',
    appId: '1:128041979938:web:ea79085cf40665cb97ba7b',
    messagingSenderId: '128041979938',
    projectId: 'fyp-sem-6-d7fa0',
    authDomain: 'fyp-sem-6-d7fa0.firebaseapp.com',
    storageBucket: 'fyp-sem-6-d7fa0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgU-yYA43PULgGGk_B5fqSt7VIkH0lehg',
    appId: '1:128041979938:android:66c69383d4a91c2397ba7b',
    messagingSenderId: '128041979938',
    projectId: 'fyp-sem-6-d7fa0',
    storageBucket: 'fyp-sem-6-d7fa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpGJf08IawMDi7IaOOkVpCCyCDLfOSEnQ',
    appId: '1:128041979938:ios:c4010f569ac50bde97ba7b',
    messagingSenderId: '128041979938',
    projectId: 'fyp-sem-6-d7fa0',
    storageBucket: 'fyp-sem-6-d7fa0.appspot.com',
    iosBundleId: 'com.example.pemaLa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpGJf08IawMDi7IaOOkVpCCyCDLfOSEnQ',
    appId: '1:128041979938:ios:a45107857d575df397ba7b',
    messagingSenderId: '128041979938',
    projectId: 'fyp-sem-6-d7fa0',
    storageBucket: 'fyp-sem-6-d7fa0.appspot.com',
    iosBundleId: 'com.example.pemaLa.RunnerTests',
  );
}
